version: '3.8'

services:
  crm-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: crm-api
    working_dir: /var/www
    volumes:
      - ./:/var/www
    ports:
      - "8000:8000"
    networks:
      - crm-network

networks:
  crm-network:
    external: true
